definitions:
  input_file:
    name: input_file
    primitive: str
  output_file:
    name: output_file
    primitive: str
  resolution:
    name: resolution
    primitive: int
flow:
  convert_to_gif:
    inputs:
      input_file:
      - seed
      output_file:
      - seed
      resolution:
      - seed
linked: true
operations:
  convert_to_gif:
    inputs:
      input_file: input_file
      output_file: output_file
      resolution: resolution
    name: convert_to_gif
    outputs: {}
    stage: processing

