# Upstream: https://github.com/actions/importer-issue-ops/blob/f5fc2781a33d92f232f415c62d021dcf6dae1e06/.github/workflows/issue_ops.yml#license=MIT
# Overlays:
# - Upstream: https://github.com/stefanbuck/github-issue-parser/blob/145e4dc5ee373ffe0129d3a3d9fc44dce64f7491/README.md#license=MIT
name: 'IssueOps: Alice: ShouldI: Contribute'
on:
  issues:
    types: [created]

permissions:
  contents: read
  issues: write

jobs:
  issue-parser:
    outputs:
      repo_name: ${{ steps.issue-parser.outputs.issueparser_repo_name }}
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
      with:
        egress-policy: audit

    - uses: stefanbuck/github-issue-parser@51ca3d60963b9cea813101636b0c596945082867 # v3
      id: issue-parser
      with:
        template-path: .github/ISSUE_TEMPLATE/new_plugin.yml
    - name: Add comment
      uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043
      with:
        issue-number: ${{ github.event.issue.number }}
        body: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

  contribute:
    needs: issue-parser
    uses: "./.github/workflows/alice_shouldi_contribute.yml"
    with:
      repo_url: "${{ needs.issue-parser.outputs.repo_url }}"
    secrets:
      GH_USER: "aliceoa"
      GH_ACCESS_TOKEN: ${{ secrets.ALICE_SHOULDI_CONTRIBUTE_ISSUE_OPS }}
